q = input("enter no 1 here ")
w = input("enter no 2 here ")
e = input("enter no 3 here ")
r = input("enter no 4 here ")
t = input("enter no 5 here ")
y = input("enter no 6 here ")
u = input("enter no 7 here ")
i = input("enter no 8 here ")

s = {q,w,e,r,t,y,u,i}
print(s)

s = set()

n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))
n = input("enter no. here")
s.add(int(n))

print(s)